[tool.poetry]
name = "dynamics-explorables"
version = "0.1.0"
description = ""
authors = ["Anastasia Golovin <anastasia.golovin@tum.de>"]
readme = "README.md"
packages = [{include = "dynamics_explorables"}]

[tool.poetry.dependencies]
python = "^3.10"
streamlit = "^1.15.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
