baseURL = 'https://dynamics-explorables.netlify.app/'
languageCode = 'en-us'
title = 'Dynamics Explorables'
theme = 'papermod'
sectionPagesMenu = 'main'
paginate = 12

[related]
  includeNewer = true
  threshold = 20
  toLower = false
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10

[params]
  env = 'production' # development or production